### ISSUE TITLE
Confusing use of "Custom configuration" screenshot for Hive flightsheet

### ISSUE THREAD

**Issue by SmartLikeTruck** [jtskxx/JETSKI-QUBIC-POOL#1]
I used the "Custom configuration" screenshot from the readme as an example to setup my flightsheet. This resulted in my rig showing up in the stats by my wallet number. Hopefully I've got it right now in that "Wallet and worker template:" has (mypoolname)-%WORKER_NAME%
![image](https://github.com/jtskxx/Jetski-Qubic-Pool/assets/116809292/3f15e6d8-38c3-4423-b5aa-947ba309c6c0)

**Comment by jtskxx** [comment]
I will add some lines to precise that miner needs to add their Pool Account name in Hiveos wallet. 
Thanks for your comments :)
